"""
Codex engine — the Codex bridge runtime.

This top-level package is the canonical home for the Codex bridge "engine":
``_CodexProxy`` and the subprocess/config helpers. It is consumed by the
orchestrator-side launcher ``orchestrator/codex_bridge_service.py``, which owns
the Codex subprocess spawn (hardened minimal-allowlist env) and imports this
module as a normal sibling package (``from codex_engine.engine import …``).
It is not an MCP tool — it is not registered in ``mcp_server/tool_registry.py``.

Spawns an OpenAI Codex CLI subprocess and routes its LLM calls through
Kim's BrowserProvider via a local HTTP proxy server.

Unlike the old file-bridge approach (polling JSON files on disk), the
Codex bridge runs a lightweight local HTTP server that speaks the OpenAI
Responses API format.  Codex is configured at launch to point its
`base_url` at this proxy, so all model traffic flows through Kim's
BrowserProvider transparently.

Architecture:
    1. Start a local aiohttp server on a random port (e.g. 127.0.0.1:PORT)
    2. Generate a temporary ~/.codex/config.toml pointing base_url at our proxy
    3. Spawn `codex <task>` as a subprocess
    4. Proxy intercepts /v1/responses, routes through BrowserProvider.complete()
    5. Returns OpenAI Responses-format JSON back to Codex
    6. When Codex exits, tear down the proxy

Auto-compaction (claw-style two-pass):
    When estimated token count exceeds the provider threshold, the proxy
    summarizes older messages via the browser LLM (first pass), then applies
    priority-based line selection to keep the summary under a character budget
    (second pass — adapted from claw's summary_compression.rs).
"""

from __future__ import annotations

import hmac
import json
import logging
import os
import re
import secrets
import shlex
import sys
import uuid
from pathlib import Path
from typing import TYPE_CHECKING, Optional

if TYPE_CHECKING:
    from orchestrator.providers.browser_provider import BrowserProvider

# K5: bracket-tag vocabulary comes from the generated event manifest so the
# text protocol cannot drift between the three runtimes.
from orchestrator.events_gen import (  # noqa: E402
    LOG_TAG_ANSWER,
    LOG_TAG_STATUS,
    LOG_TAG_TOOL,
)

logger = logging.getLogger("kim.codex_bridge")

# ── Constants ────────────────────────────────────────────────────────────────

CODEX_BINARY = "codex"

MAX_OUTPUT_BYTES = 64 * 1024 * 1024
MAX_RELAYS = 50

ALLOWED_CODEX_TOOLS = {
    "shell",
    "read_file",
    "write_file",
    "edit_file",
    "list_dir",
    "grep_search",
    "glob_search",
    "web_fetch",
    "web_search",
}

# Compaction constants (adapted from claw compact.rs)
COMPACT_KEEP_ITEMS = 20      # Keep last N items uncompressed
COMPACT_MIN_ITEMS_TO_REMOVE = 5  # Don't compact if fewer than this many items would be removed

# Per-provider context thresholds (tokens) before compaction triggers
_COMPACT_THRESHOLDS: dict[str, int] = {
    "claude": 180_000,
    "chatgpt": 100_000,
    "gemini": 800_000,
    "grok": 100_000,
    "deepseek": 60_000,
}
_DEFAULT_COMPACT_THRESHOLD = 100_000

# Deterministic provider-failure signatures for a send into a stored browser
# thread that never registered or whose tab is gone (bridge.js fail-fast
# diagnostics + BrowserProvider NEED_HELP messages). Mirrors the agent-side
# _BROWSER_SEND_FAILURE_RE in orchestrator/agent.py — kept local so the engine
# does not import the (heavy) orchestrator agent module.
_THREAD_SEND_FAILURE_RE = re.compile(
    r"Send did not register|No response turn detected|lost the active browser chat",
    re.IGNORECASE,
)


def _is_thread_send_failure(response: object) -> bool:
    if not isinstance(response, dict):
        return False
    if response.get("type") != "text":
        return False
    return bool(_THREAD_SEND_FAILURE_RE.search(str(response.get("content", ""))))


# ── Codex config generation ─────────────────────────────────────────────────


def _write_codex_config(config_path: Path, proxy_port: int, model: Optional[str] = None) -> None:
    """Write a minimal Codex config.toml pointing to our local proxy."""
    # Validate/escape the model name before interpolating into TOML (#48).
    # Only allow alphanumeric, hyphens, underscores, dots, colons, and slashes.
    import re as _re
    _safe_model = None
    if model:
        _safe_model = _re.sub(r'[^A-Za-z0-9_\-.:/ ]', '', model)[:128]
    safe_model = _safe_model or "kim-proxy-model"
    model_line = f'model = "{safe_model}"'
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(f"""\
# Auto-generated by Kim — routes Codex through Kim's browser proxy
model_provider = "kim-proxy"
{model_line}

[model_providers.kim-proxy]
name = "Kim Proxy"
base_url = "http://127.0.0.1:{proxy_port}/v1"
wire_api = "responses"
env_key = "CODEX_API_KEY"
""", encoding="utf-8")
    logger.info(f"Wrote Codex config: {config_path}")


# ── Compaction helpers ───────────────────────────────────────────────────────


def _estimate_tokens(items: list) -> int:
    """Rough token estimate: ~4 chars per token."""
    total = 0
    for item in items:
        if not isinstance(item, dict):
            continue
        for field in ("content", "output", "arguments", "text"):
            val = item.get(field, "")
            if isinstance(val, str):
                total += len(val) // 4
            elif isinstance(val, list):
                for block in val:
                    if isinstance(block, dict):
                        total += len(block.get("text", "")) // 4
    return total


def _get_compact_threshold(provider_name: str) -> int:
    name = provider_name.lower()
    for key, threshold in _COMPACT_THRESHOLDS.items():
        if key in name:
            return threshold
    return _DEFAULT_COMPACT_THRESHOLD


def _is_compaction_summary(item: object) -> bool:
    """Return True if this item is a Kim compaction summary block."""
    if not isinstance(item, dict):
        return False
    content = item.get("content", "")
    if isinstance(content, str):
        return "[CONTEXT SUMMARY" in content
    if isinstance(content, list):
        for block in content:
            if isinstance(block, dict) and "[CONTEXT SUMMARY" in block.get("text", ""):
                return True
    return False


def _fix_tool_boundary(items: list, keep_from: int) -> int:
    """Walk keep_from forward past any leading function_call_output items
    to avoid orphaning a tool result without its paired tool call."""
    idx = keep_from
    while idx < len(items):
        item = items[idx]
        if isinstance(item, dict) and item.get("type") == "function_call_output":
            idx += 1
        else:
            break
    return idx


def _compress_summary(summary_text: str, max_chars: int = 1200, max_lines: int = 24, max_line_chars: int = 160) -> str:
    """Second-pass compression (adapted from claw summary_compression.rs).

    Deduplicates, truncates long lines, and selects within a char/line budget
    using a priority ordering that keeps core fields over noise.
    """
    inner = re.sub(r"</?summary>", "", summary_text).strip()

    seen: set[str] = set()
    lines: list[str] = []
    for raw_line in inner.splitlines():
        normalized = " ".join(raw_line.split())[:max_line_chars]
        if not normalized or normalized in seen:
            continue
        seen.add(normalized)
        lines.append(normalized)

    def _priority(line: str) -> int:
        lower = line.lower()
        if any(lower.startswith(k) for k in (
            "scope:", "current work:", "tools used:", "key files:",
            "pending:", "recent user requests:", "key decisions:",
        )):
            return 0
        if any(lower.startswith(k) for k in (
            "timeline:", "previously compacted:", "newly compacted:",
        )):
            return 1
        if line.startswith(("- ", "• ", "* ", "  -")):
            return 2
        return 3

    lines.sort(key=_priority)

    selected: list[str] = []
    total_chars = 0
    for line in lines:
        if len(selected) >= max_lines:
            break
        if total_chars + len(line) + 1 > max_chars:
            break
        selected.append(line)
        total_chars += len(line) + 1

    omitted = len(lines) - len(selected)
    body = "\n".join(selected)
    if omitted > 0:
        body += f"\n[{omitted} additional context lines omitted]"

    return f"<summary>\n{body}\n</summary>"


def _merge_compact_summaries(existing: str, new_summary: str) -> str:
    """Merge existing and new compaction summaries (claw merge_compact_summaries pattern)."""
    existing_inner = re.sub(r"</?summary>", "", existing).strip()
    new_inner = re.sub(r"</?summary>", "", new_summary).strip()
    return (
        f"<summary>\nPreviously compacted context:\n{existing_inner}\n\n"
        f"Newly compacted context:\n{new_inner}\n</summary>"
    )


async def _summarize_messages(items: list, provider: "BrowserProvider") -> str:
    """Call the browser LLM to produce a <summary> XML block for the given items."""
    parts: list[str] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        role = item.get("role", "")
        itype = item.get("type", "")
        content = item.get("content", "")

        if itype == "function_call":
            name = item.get("name", "unknown")
            args = str(item.get("arguments", ""))[:400]
            parts.append(f"[TOOL CALL: {name}]\n{args}")
        elif itype == "function_call_output":
            output = item.get("output", "")
            if isinstance(output, list):
                output = " ".join(str(o) for o in output)
            parts.append(f"[TOOL RESULT]\n{str(output)[:400]}")
        elif role == "user":
            if isinstance(content, list):
                for block in content:
                    if isinstance(block, dict) and block.get("type") in ("input_text", "text"):
                        parts.append(f"[USER]\n{block.get('text', '')[:800]}")
            elif isinstance(content, str) and not _is_compaction_summary(item):
                parts.append(f"[USER]\n{content[:800]}")
        elif role == "assistant":
            if isinstance(content, list):
                for block in content:
                    if isinstance(block, dict) and block.get("type") in ("output_text", "text"):
                        parts.append(f"[ASSISTANT]\n{block.get('text', '')[:800]}")
            elif isinstance(content, str):
                parts.append(f"[ASSISTANT]\n{content[:800]}")

    transcript = "\n\n".join(parts)

    prompt = (
        "Summarize the following coding agent conversation for context compaction. "
        "Output ONLY this XML block:\n\n"
        "<summary>\n"
        "Scope: [N tool calls, M user turns]\n"
        "Tools used: [comma-separated tool names]\n"
        "Recent user requests: [brief list]\n"
        "Key files touched: [files created/modified/read]\n"
        "Current work: [what was in progress at the end]\n"
        "Key decisions: [important findings or decisions]\n"
        "Timeline: [brief chronological summary]\n"
        "</summary>\n\n"
        f"TRANSCRIPT (truncated to 8000 chars):\n{transcript[:8000]}"
    )

    try:
        response = await provider.complete(
            messages=[{"role": "user", "content": prompt}],
            tools=[],
            system="You are a precise context summarizer. Output only the requested <summary>...</summary> XML block. No other text.",
            clear_chat=True,
        )
        raw = response.get("content", "") if isinstance(response, dict) else str(response)
        match = re.search(r"<summary>(.*?)</summary>", raw, re.DOTALL)
        if match:
            return f"<summary>{match.group(1)}</summary>"
        return f"<summary>{raw[:1000]}</summary>"
    except Exception as exc:
        logger.warning(f"Summarization LLM call failed: {exc}")
        return f"<summary>Context compacted. {len(items)} messages summarized.</summary>"


# ── Local HTTP Proxy Server ──────────────────────────────────────────────────


class _CodexProxy:
    """Minimal HTTP server that translates Codex Responses API calls
    into BrowserProvider.complete() calls, with auto-compaction."""

    def __init__(
        self,
        browser_provider: "BrowserProvider",
        provider_name: str = "",
        thread_state: Optional[dict] = None,
        stateful: bool = False,
    ):
        self._provider = browser_provider
        self._provider_name = provider_name
        # Cross-task browser-thread state (codex_engine/thread_state.py sidecar,
        # loaded/saved by codex_bridge_service). Mutated in place so the service
        # can persist whatever the run left behind. ``stateful`` gates thread
        # CONTINUATION across tasks; handoff consumption works either way.
        self._thread_state: dict = thread_state if isinstance(thread_state, dict) else {}
        self._stateful = bool(stateful)
        self._server = None
        self._runner = None
        self._port = 0
        self._relay_count = 0
        self._last_sent_count = 0  # how many input_items were forwarded to the browser last relay
        self._last_proxy_response: Optional[dict] = None  # last Responses API reply sent to Codex
        self._last_tool_commands: Optional[tuple] = None  # last relay's tool-call signature (loop guard)
        # Cache: hash(json(prefix_items)) → summary_item dict
        # Avoids re-summarizing the same prefix on every Codex turn.
        self._compaction_cache: dict[int, dict] = {}
        # Per-run cryptographically random bearer token (#47).
        # Codex receives it via OPENAI_API_KEY in env; the proxy verifies it on
        # every request so any other local process cannot drive the authenticated
        # browser session through this proxy.
        self._bearer_token: str = secrets.token_urlsafe(32)

    def begin_turn(self) -> None:
        """Reset the relay budget for a new codex turn (Rb6).

        On the app-server transport one service process may host several
        turns of one session; MAX_RELAYS is a runaway guard for a single
        turn, not a lifetime cap — long legitimate sessions must not be cut
        at 50. The exec transport spawns one process per turn, so calling
        this there is a harmless no-op.
        """
        self._relay_count = 0

    def _check_auth(self, request) -> bool:
        """Return True iff the request carries the correct bearer token (#47)."""
        auth = request.headers.get("Authorization", "")
        expected = f"Bearer {self._bearer_token}"
        # constant-time compare to avoid timing side-channels
        return hmac.compare_digest(auth, expected)

    async def start(self) -> int:
        try:
            from aiohttp import web
        except ImportError:
            raise RuntimeError(
                "aiohttp is required for the Codex bridge proxy. "
                "Install with: pip install aiohttp"
            )

        app = web.Application()
        app.router.add_post("/v1/responses", self._handle_responses)
        app.router.add_post("/v1/chat/completions", self._handle_chat_completions)
        app.router.add_get("/v1/models", self._handle_models)

        self._runner = web.AppRunner(app)
        await self._runner.setup()
        site = web.TCPSite(self._runner, "127.0.0.1", 0)
        await site.start()
        self._port = site._server.sockets[0].getsockname()[1]  # type: ignore[union-attr]
        logger.info(f"Codex proxy started on port {self._port}")
        return self._port

    async def stop(self):
        if self._runner:
            try:
                await self._runner.cleanup()
            except Exception as e:
                logger.debug(f"Proxy cleanup error: {e}")

    async def _handle_models(self, request):
        from aiohttp import web
        return web.json_response({
            "object": "list",
            "data": [{"id": "kim-proxy-model", "object": "model", "created": 0, "owned_by": "kim"}],
        })

    async def _handle_responses(self, request):
        """Handle POST /v1/responses — the Codex Responses API endpoint."""
        from aiohttp import web

        if not self._check_auth(request):
            return web.json_response({"error": {"message": "Unauthorized"}}, status=401)

        self._relay_count += 1
        relay_num = self._relay_count

        if relay_num > MAX_RELAYS:
            logger.error(f"Relay count exceeded {MAX_RELAYS}")
            return web.json_response(
                {"error": {"message": "Too many relay attempts"}}, status=429,
            )

        try:
            body = await request.json()
        except Exception:
            return web.json_response({"error": {"message": "Invalid JSON body"}}, status=400)

        stream = bool(body.get("stream", False))
        logger.info(f"[relay #{relay_num}] Codex request received")

        # ── Auto-compaction ──────────────────────────────────────────────────
        input_items = body.get("input", [])
        compacted = False
        if isinstance(input_items, list) and input_items:
            threshold = _get_compact_threshold(self._provider_name)
            estimated = _estimate_tokens(input_items)
            logger.debug(f"[relay #{relay_num}] ~{estimated} estimated tokens (threshold {threshold})")

            if estimated > threshold:
                input_items = await self._apply_compaction(input_items, relay_num)
                body = {**body, "input": input_items}
                compacted = True
        # ────────────────────────────────────────────────────────────────────

        is_first_relay = self._last_sent_count == 0 or compacted

        continuing_thread = False
        if is_first_relay:
            continuing_thread = (
                self._stateful
                and not compacted
                and bool(self._thread_state.get("sent_instructions"))
            )
            if continuing_thread:
                # Stateful mode: the session's browser thread already holds the
                # codex system prompt from a previous task — send only the new
                # task items (env context + user task), not the instructions.
                prompt = _extract_delta_prompt(input_items) or _extract_prompt_from_responses_request(body)
                clear_chat = False
                if hasattr(self._provider, "mark_thread_continuation"):
                    self._provider.mark_thread_continuation()
                logger.info(
                    f"[relay #{relay_num}] First relay — continuing stored browser thread "
                    f"(delta only, {self._thread_state.get('turns', 0)} prior turns)"
                )
            else:
                # First relay or post-compaction: send full context and start a fresh browser chat.
                prompt = _extract_prompt_from_responses_request(body)
                clear_chat = True
                # Ensure system prompt is re-injected when the new browser chat opens.
                if hasattr(self._provider, '_sent_system_prompt'):
                    self._provider._sent_system_prompt = False
                logger.info(f"[relay #{relay_num}] First relay — sending full context")
            # ChatGPT weighs the END of a long prompt far more than the top —
            # codex's forwarded schemas bury the terminal rules, and turn 1
            # comes back as "save this as game.html" prose. A compact reminder
            # at the tail fixes the recency bias.
            if bool(self._provider_name) and "chatgpt" in self._provider_name.lower():
                prompt += (
                    "\n\n(Format reminder: reply with ONE short narration line, then "
                    "EXACTLY ONE shell command in a single ```bash block — create files "
                    "with a command, never paste code for me to save myself.)"
                )
            self._last_sent_count = len(input_items) if isinstance(input_items, list) else 0
        else:
            # Subsequent relay: send only new user-side items since the last relay.
            delta_items = input_items[self._last_sent_count:] if isinstance(input_items, list) else []

            # If Codex is only sending "Continue." keepalive messages (no tool results),
            # return the cached last response directly — no need to call the browser again.
            # This breaks the Continue. loop that occurs when Codex keeps asking for more
            # after a plain-text (non-tool-call) answer.
            if delta_items and _is_continue_only_delta(delta_items) and self._last_proxy_response is not None:
                # Consume the keepalive items: without advancing the cursor the
                # stale "Continue." messages would be re-included in every later
                # delta and forwarded to the browser as duplicate [USER] noise.
                self._last_sent_count = len(input_items)
                logger.info(f"[relay #{relay_num}] Continue.-only delta — returning cached response")
                return _sse_or_json(stream, self._last_proxy_response)

            if delta_items:
                prompt = _extract_delta_prompt(delta_items)
                # Terminal mode: an empty tool result reads as "nothing
                # happened", so ChatGPT re-sends `open x` forever. Spell out
                # the stop condition on every tool-result relay.
                is_chatgpt = bool(self._provider_name) and "chatgpt" in self._provider_name.lower()
                if is_chatgpt and prompt and "[TOOL RESULT]" in prompt:
                    prompt += (
                        "\n\n(Those commands already ran — no output means success. "
                        "If the request is now fully complete, reply with just DONE. "
                        "Do NOT re-send a command that already ran.)"
                    )
                self._last_sent_count = len(input_items)
                logger.info(f"[relay #{relay_num}] Delta relay — {len(delta_items)} new items")
            else:
                # No new items at all — return cached response or terminal stub
                if self._last_proxy_response is not None:
                    logger.info(f"[relay #{relay_num}] Empty delta — returning cached response")
                    return _sse_or_json(stream, self._last_proxy_response)
                prompt = "Continue."
                logger.info(f"[relay #{relay_num}] Empty delta (no cache) — sending 'Continue.'")
            clear_chat = False

        # A pending compact handoff seeds the first send of a fresh chat only.
        handoff = None
        if is_first_relay and clear_chat:
            handoff = str(self._thread_state.get("handoff") or "").strip() or None
            if handoff and os.environ.get("KIM_DEBUG_COMPACT") == "1":
                # Temporary verification aid: confirm the compact handoff is
                # injected into the fresh chat (KIM_DEBUG_COMPACT=1).
                print(
                    json.dumps({
                        "type": "status",
                        "message": f"[compact] seeding fresh chat with a {len(handoff)}-char handoff",
                    }),
                    flush=True,
                )

        try:
            extra_kwargs = {"handoff": handoff} if handoff else {}
            response = await self._provider.complete(
                messages=[{"role": "user", "content": prompt}],
                tools=[],
                system=_system_prompt_for(self._provider_name),
                clear_chat=clear_chat,
                **extra_kwargs,
            )
            if continuing_thread and _is_thread_send_failure(response):
                # The stored thread is unresponsive/gone — degrade once to the
                # legacy behavior: fresh chat, full context, pending handoff.
                logger.warning(f"[relay #{relay_num}] Stored-thread send failed — retrying on a fresh chat")
                print(f"{LOG_TAG_STATUS} Stored thread did not respond — retrying on a fresh chat…", flush=True)
                prompt = _extract_prompt_from_responses_request(body)
                clear_chat = True
                handoff = str(self._thread_state.get("handoff") or "").strip() or None
                if hasattr(self._provider, '_sent_system_prompt'):
                    self._provider._sent_system_prompt = False
                extra_kwargs = {"handoff": handoff} if handoff else {}
                response = await self._provider.complete(
                    messages=[{"role": "user", "content": prompt}],
                    tools=[],
                    system=_system_prompt_for(self._provider_name),
                    clear_chat=True,
                    **extra_kwargs,
                )
        except Exception as e:
            logger.error(f"[relay #{relay_num}] Browser LLM call failed: {e}")
            return web.json_response(
                {"error": {"message": f"LLM call failed: {e}"}}, status=502,
            )

        response = await self._nudge_contract_retry(response, relay_num)

        self._note_relay_result(
            is_first_relay=is_first_relay,
            cleared_chat=clear_chat,
            consumed_handoff=handoff,
            response=response,
        )

        # Narrate the model's prose FIRST ("I'll drop a simple click-the-box
        # game…"), then the humanized command lines from _announce_commands —
        # this is the visible "thinking" for a browser model whose real chain
        # of thought can't be scraped.
        _surface_relay_reasoning(response, relay_num)
        responses_reply = _provider_response_to_responses_api(
            response, relay_num, request_tools=body.get("tools"),
            metrics=self._thread_state.setdefault("repairs", {}),
        )
        # Loop guard: if this relay's tool calls repeat the previous relay's —
        # identical, or a subset of sub-commands that already ran (`open x`
        # after `printf … && open x`) — the model is looping (an empty tool
        # result gives it no signal to stop). Re-running achieves nothing, so
        # end the turn with a plain final answer — codex sees no tool call and
        # finishes, which is the "it never registers as done" fix.
        cmds = _tool_command_signature(responses_reply)
        if _is_repeat_of_previous(cmds, self._last_tool_commands):
            logger.info(f"[relay #{relay_num}] Repeated tool call {cmds} — ending turn (loop guard)")
            print(f"{LOG_TAG_STATUS} Command already ran — finishing up…", flush=True)
            # Honest final answer: name the command that actually repeated —
            # never claim work ("the file was created") the commands don't show.
            subs = sorted(_signature_subcommands(cmds))
            if subs:
                did = " and ".join(_humanize_single(s).lower() for s in subs)
                done_text = f"Done — {did} already ran; nothing left to do."
            else:
                done_text = "Done — that command already ran; nothing left to do."
            responses_reply = _make_responses_text_reply(
                f"resp_{uuid.uuid4().hex[:16]}", done_text
            )
            cmds = None
        self._last_tool_commands = cmds
        self._last_proxy_response = responses_reply

        return _sse_or_json(stream, responses_reply)

    async def _nudge_contract_retry(self, response: dict, relay_num: int) -> dict:
        """One-shot format re-ask when a reply ignored the JSON contract.

        A prose reply ("I'll create the files…") parses as a FINAL ANSWER, so
        codex ends the turn having executed nothing — the model narrated its
        actions instead of emitting tool_calls. Re-ask once on the same thread;
        if the retry parses, use it, otherwise keep the original reply.
        """
        if not isinstance(response, dict) or response.get("type") != "text":
            return response
        content = response.get("content", "")
        if not isinstance(content, str) or not content.strip():
            return response
        if _parse_contract(content) is not None:
            return response
        if _is_done_reply(content):
            # A bare DONE is the terminal-mode finish signal, not a missing
            # command — nudging it makes the model say DONE twice and falsely
            # burns the thread.
            return response
        if _is_thread_send_failure(response):
            return response
        if _reply_has_salvageable_actions(content):
            # The prose carries executable actions (json/shell fences or a
            # save-as file directive) — the converter executes those directly;
            # nudging would waste a round trip (and protocol-refusing models
            # answer the nudge with another refusal).
            logger.info(f"[relay #{relay_num}] Prose reply has salvageable actions — executing, no nudge")
            return response
        logger.info(f"[relay #{relay_num}] Reply had no actionable command — sending one nudge")
        _count_repair(self._thread_state.setdefault("repairs", {}), "nudges")
        print(f"{LOG_TAG_STATUS} Reply had no runnable command — asking for it…", flush=True)
        is_chatgpt = bool(self._provider_name) and "chatgpt" in self._provider_name.lower()
        nudge = _TERMINAL_NUDGE if is_chatgpt else _CONTRACT_NUDGE
        try:
            retry = await self._provider.complete(
                messages=[{"role": "user", "content": nudge}],
                tools=[],
                system=_system_prompt_for(self._provider_name),
                clear_chat=False,
            )
        except Exception as e:
            logger.warning(f"[relay #{relay_num}] Contract nudge failed ({e}) — keeping original reply")
            return response
        retry_content = retry.get("content") if isinstance(retry, dict) else None
        retry_parsed = _parse_contract(retry_content)
        if retry_parsed is not None:
            retry_text = str(retry_parsed.get("text") or "")
            if (
                not retry_parsed.get("tool_calls")
                and not _reply_has_salvageable_actions(retry_text)
                and _SELF_HELP_RE.search(retry_text)
            ):
                # Format-compliant dodge: a final answer telling the USER to
                # save files / run commands after being told actions must be
                # tool_calls. The thread won't act — don't resume it.
                self._thread_state["burned"] = True
                logger.warning(
                    f"[relay #{relay_num}] Nudge answered with do-it-yourself instructions — thread burned"
                )
            return retry
        if _reply_has_salvageable_actions(retry_content):
            # Refused the JSON reply but handed over the work — good enough.
            return retry
        if _is_done_reply(retry_content):
            # The nudge was answered with the finish signal — the task is
            # done; don't burn a thread that just completed cleanly.
            return retry
        # The thread ignored the contract even after an explicit format
        # nudge — it has talked itself out of the protocol (each refusal in
        # a chat makes the next more likely). Mark it burned so the next
        # task starts a fresh chat instead of resuming this one.
        self._thread_state["burned"] = True
        logger.warning(f"[relay #{relay_num}] Thread ignored the format nudge — marked burned")
        return response

    def _note_relay_result(
        self,
        *,
        is_first_relay: bool,
        cleared_chat: bool,
        consumed_handoff: Optional[str],
        response: object,
    ) -> None:
        """Update the cross-task thread-state accounting after a browser send."""
        state = self._thread_state
        if cleared_chat:
            # Fresh chat: restart the thread accounting.
            state["turns"] = 0
            state["est_tokens"] = 0
        if consumed_handoff:
            state["handoff"] = None
        if is_first_relay and self._stateful:
            # Only mark the thread as holding the system prompt in stateful mode.
            # Legacy mode clears the chat every task, so persisting this would
            # wrongly make the first stateful task skip the system prompt.
            state["sent_instructions"] = True
        usage = response.get("usage", {}) if isinstance(response, dict) else {}
        if not isinstance(usage, dict):
            usage = {}
        state["turns"] = int(state.get("turns") or 0) + 1
        state["est_tokens"] = (
            int(state.get("est_tokens") or 0)
            + int(usage.get("input") or 0)
            + int(usage.get("output") or 0)
        )

    async def _handle_chat_completions(self, request):
        """Handle POST /v1/chat/completions — standard OpenAI chat format."""
        from aiohttp import web

        if not self._check_auth(request):
            return web.json_response({"error": {"message": "Unauthorized"}}, status=401)

        self._relay_count += 1
        relay_num = self._relay_count

        if relay_num > MAX_RELAYS:
            return web.json_response({"error": {"message": "Too many relay attempts"}}, status=429)

        try:
            body = await request.json()
        except Exception:
            return web.json_response({"error": {"message": "Invalid JSON body"}}, status=400)

        logger.info(f"[relay #{relay_num}] Chat completions request received")

        # ── Auto-compaction ──────────────────────────────────────────────────
        messages = body.get("messages", [])
        if isinstance(messages, list) and messages:
            threshold = _get_compact_threshold(self._provider_name)
            estimated = _estimate_tokens(messages)
            logger.debug(f"[relay #{relay_num}] ~{estimated} estimated tokens (threshold {threshold})")
            if estimated > threshold:
                messages = await self._apply_compaction_chat(messages, relay_num)
                body = {**body, "messages": messages}
        # ────────────────────────────────────────────────────────────────────

        prompt = _extract_prompt_from_chat_request(body)

        try:
            response = await self._provider.complete(
                messages=[{"role": "user", "content": prompt}],
                tools=[],
                system=_system_prompt_for(self._provider_name),
                clear_chat=True,
            )
        except Exception as e:
            logger.error(f"[relay #{relay_num}] Browser LLM call failed: {e}")
            return web.json_response({"error": {"message": f"LLM call failed: {e}"}}, status=502)

        reply = _provider_response_to_chat_completions(response, relay_num)
        _surface_relay_reasoning(response, relay_num)

        return web.json_response(reply)

    async def _apply_compaction_chat(self, messages: list, relay_num: int) -> list:
        """Compaction for chat completions format (role/content messages)."""
        existing_summary: Optional[str] = None
        summary_start = 0

        # Check if first non-system message is a compaction summary
        for i, msg in enumerate(messages):
            if not isinstance(msg, dict):
                continue
            if msg.get("role") == "system":
                continue
            content = msg.get("content", "")
            if isinstance(content, str) and "[CONTEXT SUMMARY" in content:
                existing_summary = content
                summary_start = i + 1
            break

        system_msgs = [m for m in messages if isinstance(m, dict) and m.get("role") == "system"]
        non_system = messages[summary_start:] if summary_start else [
            m for m in messages if not (isinstance(m, dict) and m.get("role") == "system")
        ]

        keep_from_raw = max(0, len(non_system) - COMPACT_KEEP_ITEMS)
        if keep_from_raw < COMPACT_MIN_ITEMS_TO_REMOVE:
            return messages

        to_summarize = non_system[:keep_from_raw]
        to_keep = non_system[keep_from_raw:]

        try:
            prefix_key = hash(json.dumps(to_summarize, default=str, sort_keys=True))
        except Exception:
            prefix_key = hash(str(to_summarize))

        if prefix_key in self._compaction_cache:
            logger.info(f"[relay #{relay_num}] [compaction] Cache hit — reusing summary")
            cached = self._compaction_cache[prefix_key]
            return system_msgs + [cached] + list(to_keep)

        logger.info(f"[relay #{relay_num}] [compaction] Summarizing {len(to_summarize)} messages, keeping {len(to_keep)}")
        print(f"{LOG_TAG_STATUS} Compacting context — summarizing {len(to_summarize)} messages…", flush=True)

        # Convert chat messages to codex-bridge item format for the summarizer
        items_for_summary = [
            {"role": m.get("role", "user"), "content": m.get("content", "")}
            for m in to_summarize if isinstance(m, dict)
        ]
        new_summary = await _summarize_messages(items_for_summary, self._provider)

        if existing_summary:
            merged = _merge_compact_summaries(existing_summary, new_summary)
        else:
            merged = new_summary

        compressed = _compress_summary(merged)

        summary_msg = {
            "role": "user",
            "content": f"[CONTEXT SUMMARY — previous conversation compacted]\n{compressed}",
        }

        self._compaction_cache[prefix_key] = summary_msg
        print(f"{LOG_TAG_STATUS} Context compacted — summary is {len(compressed)} chars", flush=True)

        return system_msgs + [summary_msg] + list(to_keep)

    async def _apply_compaction(self, items: list, relay_num: int) -> list:
        """Run claw-style two-pass compaction, with prefix-hash caching."""
        # Separate existing summary (if any) from the rest
        existing_summary: Optional[str] = None
        summary_start = 0
        if _is_compaction_summary(items[0]):
            first_content = items[0].get("content", "")
            if isinstance(first_content, list):
                for block in first_content:
                    if isinstance(block, dict):
                        existing_summary = block.get("text", "")
                        break
            elif isinstance(first_content, str):
                existing_summary = first_content
            summary_start = 1

        effective = items[summary_start:]

        # Determine split point
        keep_from_raw = max(0, len(effective) - COMPACT_KEEP_ITEMS)
        keep_from = _fix_tool_boundary(effective, keep_from_raw)

        if len(effective[:keep_from]) < COMPACT_MIN_ITEMS_TO_REMOVE:
            logger.debug("[compaction] Not enough items to compact, skipping")
            return items

        to_summarize = effective[:keep_from]
        to_keep = effective[keep_from:]

        # Cache key: hash of the prefix that would be summarized
        try:
            prefix_key = hash(json.dumps(to_summarize, default=str, sort_keys=True))
        except Exception:
            prefix_key = hash(str(to_summarize))

        if prefix_key in self._compaction_cache:
            logger.info(f"[relay #{relay_num}] [compaction] Cache hit — reusing summary")
            cached_summary_item = self._compaction_cache[prefix_key]
            return [cached_summary_item] + list(to_keep)

        # First pass: LLM summarization
        logger.info(f"[relay #{relay_num}] [compaction] Summarizing {len(to_summarize)} items, keeping {len(to_keep)}")
        print(f"{LOG_TAG_STATUS} Compacting context — summarizing {len(to_summarize)} messages…", flush=True)

        new_summary = await _summarize_messages(to_summarize, self._provider)

        # Merge with existing summary if we had one
        if existing_summary:
            merged = _merge_compact_summaries(existing_summary, new_summary)
        else:
            merged = new_summary

        # Second pass: compress
        compressed = _compress_summary(merged)

        summary_item: dict = {
            "role": "user",
            "content": [
                {
                    "type": "input_text",
                    "text": f"[CONTEXT SUMMARY — previous conversation compacted]\n{compressed}",
                }
            ],
        }

        self._compaction_cache[prefix_key] = summary_item

        print(f"{LOG_TAG_STATUS} Context compacted — summary is {len(compressed)} chars", flush=True)
        logger.info(f"[compaction] Done. Summary: {len(compressed)} chars")

        return [summary_item] + list(to_keep)


# ── Request/Response translation ─────────────────────────────────────────────


def _is_continue_only_delta(items: list) -> bool:
    """Return True if the delta contains only Codex 'Continue.' keepalive user messages.

    Codex appends 'Continue.' (optionally followed by a completion-token instruction)
    to prompt the model to keep going.  When the last browser response was a plain
    text answer (no tool calls), these keepalive messages should not reach the browser.
    """
    has_user = False
    for item in items:
        if not isinstance(item, dict):
            continue
        if item.get("type") == "function_call_output":
            return False  # Real tool result present — not Continue.-only
        role = item.get("role", "")
        if role == "user":
            has_user = True
            content = item.get("content", "")
            text = ""
            if isinstance(content, str):
                text = content.strip()
            elif isinstance(content, list):
                for block in content:
                    if isinstance(block, dict) and block.get("type") in ("input_text", "text"):
                        text += block.get("text", "")
                text = text.strip()
            # Allow "Continue." possibly followed by the append-marker
            # instruction. Match the exact Codex keepalive prefix (with the
            # period) — a real user message like "Continue working on X" must
            # NOT be swallowed by the cached-response short-circuit. Today user
            # text only appears mid-turn as Codex keepalives, but mid-turn user
            # injection (turn/steer) will change that.
            if not text.startswith("Continue."):
                return False
    return has_user


def _sse_or_json(stream: bool, payload: dict):
    """Return payload as SSE stream or plain JSON depending on the stream flag."""
    from aiohttp import web
    return _make_sse_response(payload) if stream else web.json_response(payload)


def _make_sse_response(responses_reply: dict):
    """Wrap a Responses API dict as an SSE stream for Codex streaming requests.

    Codex builds its item stream from the granular ``response.output_item.*``
    events — a bare ``response.completed`` carrying the output is silently
    ignored (verified against codex-cli 0.134: without the item events the
    agent message never surfaces, ``exec --json`` emits no ``item.completed``,
    and ``-o`` writes an empty file). So every output item must be streamed as
    added → (text/argument deltas) → done before the final completed event.
    """
    from aiohttp import web

    in_progress = dict(responses_reply)
    in_progress["status"] = "in_progress"
    events: list[dict] = [{"type": "response.created", "response": in_progress}]

    for idx, item in enumerate(responses_reply.get("output") or []):
        if not isinstance(item, dict):
            continue
        item_type = item.get("type", "")
        item_id = str(item.get("id") or f"item_{idx}")
        item = {**item, "id": item_id}

        if item_type == "message":
            text = "".join(
                str(block.get("text") or "")
                for block in (item.get("content") or [])
                if isinstance(block, dict) and block.get("type") == "output_text"
            )
            events.append({
                "type": "response.output_item.added",
                "output_index": idx,
                "item": {**item, "content": [], "status": "in_progress"},
            })
            events.append({
                "type": "response.output_text.delta",
                "item_id": item_id, "output_index": idx, "content_index": 0,
                "delta": text,
            })
            events.append({
                "type": "response.output_text.done",
                "item_id": item_id, "output_index": idx, "content_index": 0,
                "text": text,
            })
            events.append({
                "type": "response.output_item.done",
                "output_index": idx,
                "item": {**item, "status": "completed"},
            })
        elif item_type == "function_call":
            arguments = str(item.get("arguments") or "{}")
            events.append({
                "type": "response.output_item.added",
                "output_index": idx,
                "item": {**item, "arguments": "", "status": "in_progress"},
            })
            events.append({
                "type": "response.function_call_arguments.delta",
                "item_id": item_id, "output_index": idx,
                "delta": arguments,
            })
            events.append({
                "type": "response.function_call_arguments.done",
                "item_id": item_id, "output_index": idx,
                "arguments": arguments,
            })
            events.append({
                "type": "response.output_item.done",
                "output_index": idx,
                "item": {**item, "status": "completed"},
            })
        else:
            events.append({
                "type": "response.output_item.added", "output_index": idx, "item": item,
            })
            events.append({
                "type": "response.output_item.done", "output_index": idx, "item": item,
            })

    events.append({"type": "response.completed", "response": responses_reply})
    lines = [f"data: {json.dumps(ev)}\n\n" for ev in events]
    lines.append("data: [DONE]\n\n")
    return web.Response(
        body="".join(lines).encode(),
        content_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


def _extract_delta_prompt(items: list) -> str:
    """Build a prompt string from only new (delta) Responses API items.

    Skips assistant echoes and function_call items — the browser chat already
    has those. Only forwards what the browser hasn't seen: user messages and
    tool results.
    """
    parts: list[str] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        itype = item.get("type", "")
        role = item.get("role", "")
        content = item.get("content", "")

        if itype == "function_call_output":
            output = item.get("output", "")
            if isinstance(output, list):
                output = " ".join(str(o) for o in output)
            # Generous cap: at 2000 chars real tool results (file reads, test
            # output) were silently cut and the model acted on incomplete data.
            parts.append(f"[TOOL RESULT]\n{str(output)[:6000]}")
        elif role == "user":
            if isinstance(content, list):
                for block in content:
                    if isinstance(block, dict) and block.get("type") in ("input_text", "text"):
                        parts.append(f"[USER]\n{block.get('text', '')}")
            elif isinstance(content, str):
                parts.append(f"[USER]\n{content}")
        # assistant and function_call items are already in the browser chat — skip them
    return "\n\n".join(parts)


def _render_codex_tools(tools: object) -> str:
    """Render Codex's request `tools` array as a prompt section.

    Codex passes its tool definitions (shell, apply_patch, update_plan, …) as
    structured JSON in the request body — NOT inside `instructions`. Without
    this section the browser model is told to emit tool_calls while seeing no
    tool list, and honesty-tuned models refuse outright ("there are no tools
    available").
    """
    if not isinstance(tools, list):
        return ""
    rendered = []
    for tool in tools:
        if not isinstance(tool, dict):
            continue
        # Responses API is flat; chat completions nests under "function".
        fn_raw = tool.get("function")
        fn = fn_raw if isinstance(fn_raw, dict) else {}
        name = tool.get("name") or fn.get("name")
        if name:
            entry = f"- {name}"
            desc = str(tool.get("description") or fn.get("description") or "").strip()
            if desc:
                entry += f": {desc}"
            params = tool.get("parameters") or fn.get("parameters")
            if params:
                entry += f"\n  input schema: {json.dumps(params, ensure_ascii=False)}"
            rendered.append(entry)
        elif tool.get("type"):
            rendered.append(f"- {tool['type']}")
    if not rendered:
        return ""
    return "[AVAILABLE CODEX TOOLS]\n" + "\n".join(rendered) + "\n"


_EXEC_ALIASES = {
    "exec", "shell", "bash", "sh", "zsh", "run", "execute", "terminal",
    "cmd", "command", "run_command", "run_shell_command", "execute_command",
}


def _normalize_tool_calls(tool_calls: list, request_tools: object) -> list:
    """Snap model-invented tool names onto the real tools from the request.

    Browser models routinely shorten or alias tool names ("exec" for
    "exec_command", "shell" for the exec tool) — codex then rejects the call
    as an unknown tool and the whole task stalls. The proxy knows the real
    tool list from the request body, so repair what is unambiguous. Also
    coerces a "command" argument (string or argv list) into the "cmd" string
    the codex exec tool requires.
    """
    by_name: dict = {}
    if isinstance(request_tools, list):
        for tool in request_tools:
            if not isinstance(tool, dict):
                continue
            fn_raw = tool.get("function")
            fn = fn_raw if isinstance(fn_raw, dict) else {}
            name = tool.get("name") or fn.get("name")
            if name:
                by_name[str(name)] = tool
    if not by_name:
        return tool_calls

    exec_tool = next(
        (n for n in by_name if "exec" in n.lower() or "shell" in n.lower() or "command" in n.lower()),
        None,
    )

    normalized = []
    for tc in tool_calls:
        if not isinstance(tc, dict):
            normalized.append(tc)
            continue
        name = str(tc.get("name") or "")
        if name and name not in by_name:
            fixed = None
            low = name.lower()
            if len(low) >= 3:
                fixed = next(
                    (n for n in by_name if n.lower().startswith(low) or low.startswith(n.lower())),
                    None,
                )
            if fixed is None and low in _EXEC_ALIASES:
                fixed = exec_tool
            if fixed:
                logger.info(f"Normalized tool name {name!r} -> {fixed!r}")
                tc = {**tc, "name": fixed}
        # Coerce command->cmd for the exec tool (argv lists become one string).
        target = by_name.get(str(tc.get("name") or ""))
        if target is not None:
            required = ((target.get("parameters") or {}).get("required")) or []
            inp = tc.get("input")
            if "cmd" in required and isinstance(inp, dict) and "cmd" not in inp and "command" in inp:
                cmd_val = inp["command"]
                if isinstance(cmd_val, list):
                    cmd_val = shlex.join(str(part) for part in cmd_val)
                new_inp = {k: v for k, v in inp.items() if k != "command"}
                new_inp["cmd"] = str(cmd_val)
                tc = {**tc, "input": new_inp}
        normalized.append(tc)
    return normalized


def _reply_has_salvageable_actions(content: object) -> bool:
    """True when a non-contract reply still describes executable work."""
    return bool(
        _extract_json_tool_fences(content)
        or _extract_shell_blocks(content)
        or _extract_file_directive(content) is not None
    )


def _humanize_single(cmd: str) -> str:
    """One shell command → a short, human activity line ('Creating game.html')."""
    cmd = cmd.strip()
    low = cmd.lower()
    m = re.search(r">\s*([^\s;&|>]+\.\w+)", cmd)
    if m and re.match(r"(printf|cat|tee|echo)\b", low):
        return f"Creating {m.group(1)}"
    m = re.match(r"open\s+(?:-\w+\s+)*([^\s;&|]+)", cmd)
    if m:
        return f"Opening {m.group(1)}"
    m = re.match(r"mkdir\s+(?:-p\s+)?([^\s;&|]+)", cmd)
    if m:
        return f"Creating folder {m.group(1)}"
    if re.match(r"(npm\s+(i|install)|yarn(\s+install)?|pnpm\s+install)\b", low):
        return "Installing dependencies"
    m = re.match(r"(?:npm run|node|python3?|npx)\s+([^\s;&|]+)", cmd)
    if m:
        return f"Running {m.group(1)}"
    short = cmd if len(cmd) <= 50 else cmd[:50] + "…"
    return f"Running: {short}"


def _humanize_command(cmd: str) -> str:
    """Full command (possibly `a && b`) → readable line ('Creating x then Opening x')."""
    cmd = (cmd or "").strip()
    if not cmd:
        return "Running command"
    parts = [p for p in re.split(r"\s*&&\s*", cmd) if p.strip()]
    if len(parts) > 1:
        return " then ".join(_humanize_single(p) for p in parts)
    return _humanize_single(cmd)


def _announce_commands(tool_calls: list) -> None:
    """Emit a clean per-command activity line instead of dumping raw commands."""
    seen = []
    for tc in tool_calls or []:
        if not isinstance(tc, dict):
            continue
        cmd = (tc.get("input") or {}).get("cmd", "")
        if isinstance(cmd, str) and cmd.strip():
            line = _humanize_command(cmd)
            if line not in seen:
                seen.append(line)
                print(f"{LOG_TAG_STATUS} {line}…", flush=True)


def _salvage_action_reply(content: object, request_tools: object) -> Optional[list]:
    """Convert a non-tool-call reply's described actions into real tool calls.

    Shapes, in priority order: a ```json tool-call fence, ```bash/sh command
    fences, or a "save this code as X" directive + fenced file body. Returns
    normalized tool calls (announcing them as clean activity lines), or None
    when the reply describes nothing executable.
    """
    calls = None
    json_calls = _extract_json_tool_fences(content)
    if json_calls:
        calls = _normalize_tool_calls(json_calls, request_tools)
    if not calls:
        blocks = _extract_shell_blocks(content)
        if blocks:
            calls = _normalize_tool_calls(
                [{"name": "exec", "input": {"cmd": block}} for block in blocks],
                request_tools,
            )
    if not calls:
        directive = _extract_file_directive(content)
        if directive is not None:
            name, body, wants_open = directive
            calls = _normalize_tool_calls(
                _file_directive_tool_calls(name, body, wants_open), request_tools
            )
    if calls:
        _announce_commands(calls)
        return calls
    return None


def _extract_prompt_from_responses_request(body: dict) -> str:
    """Extract a human-readable prompt from a Codex Responses API request."""
    parts = []

    instructions = body.get("instructions")
    if instructions:
        parts.append(f"[SYSTEM PROMPT]\n{instructions}\n")

    tools_section = _render_codex_tools(body.get("tools"))
    if tools_section:
        parts.append(tools_section)

    input_items = body.get("input")
    if isinstance(input_items, str):
        parts.append(f"[USER]\n{input_items}\n")
    elif isinstance(input_items, list):
        for item in input_items:
            if isinstance(item, str):
                parts.append(f"[USER]\n{item}\n")
            elif isinstance(item, dict):
                role = item.get("role", "user").upper()
                content = item.get("content", "")
                if isinstance(content, list):
                    for block in content:
                        if isinstance(block, dict):
                            btype = block.get("type", "")
                            if btype in ("input_text", "text"):
                                parts.append(f"[{role}]\n{block.get('text', '')}\n")
                            elif btype == "output_text":
                                parts.append(f"[ASSISTANT]\n{block.get('text', '')}\n")
                elif isinstance(content, str):
                    parts.append(f"[{role}]\n{content}\n")

    return "\n".join(parts) if parts else str(body)


def _extract_prompt_from_chat_request(body: dict) -> str:
    """Convert a chat completions request body into a single prompt string."""
    parts = []
    tools_section = _render_codex_tools(body.get("tools"))
    if tools_section:
        parts.append(tools_section)
    for msg in body.get("messages", []):
        if not isinstance(msg, dict):
            continue
        role = msg.get("role", "user").upper()
        content = msg.get("content", "")
        if isinstance(content, str):
            if role == "SYSTEM":
                parts.append(f"[SYSTEM PROMPT]\n{content}\n")
            else:
                parts.append(f"[{role}]\n{content}\n")
        elif isinstance(content, list):
            for block in content:
                if isinstance(block, dict) and block.get("type") == "text":
                    parts.append(f"[{role}]\n{block.get('text', '')}\n")
    return "\n".join(parts) if parts else str(body)


def _provider_response_to_chat_completions(response: dict, relay_num: int) -> dict:
    """Convert a BrowserProvider response to OpenAI chat completions format."""
    resp_id = f"chatcmpl_{uuid.uuid4().hex[:16]}"

    if not isinstance(response, dict):
        return _make_chat_text_reply(resp_id, str(response))

    content = response.get("content", "")
    if isinstance(content, str):
        parsed = None
        try:
            parsed = json.loads(content)
        except (json.JSONDecodeError, TypeError):
            try:
                import json_repair  # type: ignore[import-not-found]
                parsed = json_repair.repair_json(content, return_objects=True)
            except Exception:
                pass

        if isinstance(parsed, dict):
            text = parsed.get("text", "")
            tool_calls = parsed.get("tool_calls", [])
            if tool_calls:
                return _make_chat_tool_reply(resp_id, text, tool_calls)
            return _make_chat_text_reply(resp_id, text or content)

        return _make_chat_text_reply(resp_id, content)

    return _make_chat_text_reply(resp_id, str(content))


def _make_chat_text_reply(resp_id: str, text: str) -> dict:
    return {
        "id": resp_id,
        "object": "chat.completion",
        "created": 0,
        "model": "kim-proxy-model",
        "choices": [{
            "index": 0,
            "message": {"role": "assistant", "content": text},
            "finish_reason": "stop",
        }],
        "usage": {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0},
    }


def _make_chat_tool_reply(resp_id: str, text: str, tool_calls: list) -> dict:
    formatted_calls = []
    for tc in tool_calls:
        if isinstance(tc, dict):
            formatted_calls.append({
                "id": f"call_{uuid.uuid4().hex[:12]}",
                "type": "function",
                "function": {
                    "name": tc.get("name", "unknown"),
                    "arguments": json.dumps(tc.get("input", {})),
                },
            })
    return {
        "id": resp_id,
        "object": "chat.completion",
        "created": 0,
        "model": "kim-proxy-model",
        "choices": [{
            "index": 0,
            "message": {
                "role": "assistant",
                "content": text or None,
                "tool_calls": formatted_calls,
            },
            "finish_reason": "tool_calls" if formatted_calls else "stop",
        }],
        "usage": {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0},
    }


def _coerce_contract_dict(parsed: object) -> Optional[dict]:
    """Coerce a parsed reply into one contract dict.

    Browser models sometimes emit SEVERAL JSON objects in one reply — the
    observed live case: a tool_calls object, an orphaned {"name","input"}
    fragment split off by a malformed bracket, and a fabricated
    completion-report text ("pong game created and opened") role-playing the
    runtime's answer. json_repair returns those as a list; salvage the real
    actions and drop the fabricated epilogue.
    """
    if isinstance(parsed, dict):
        return parsed
    if not isinstance(parsed, list):
        return None
    dicts = [d for d in parsed if isinstance(d, dict)]
    base = next((d for d in dicts if d.get("tool_calls")), None)
    if base is not None:
        # Orphaned tool-call-shaped fragments belong to the same array.
        extras = [
            d for d in dicts
            if d is not base and "name" in d and "input" in d
            and "tool_calls" not in d and "text" not in d
        ]
        if extras:
            base = {**base, "tool_calls": list(base["tool_calls"]) + extras}
        return base
    return next((d for d in dicts if "text" in d), None)


def _parse_contract(content: object) -> Optional[dict]:
    """Parse a browser reply against the bridge contract ({"text", "tool_calls"}).

    Returns the parsed dict, or None when the reply is not contract JSON
    (prose, code fences, bare strings, …). Shared by the reply converter and
    the one-shot format nudge so both agree on what counts as a violation.
    """
    if not isinstance(content, str) or not content.strip():
        return None
    parsed = None
    try:
        parsed = json.loads(content)
    except (json.JSONDecodeError, TypeError):
        try:
            import json_repair  # type: ignore[import-not-found]
            parsed = json_repair.repair_json(content, return_objects=True)
        except Exception:
            return None
    return _coerce_contract_dict(parsed)


# Fenced shell blocks in a prose reply. Some models (ChatGPT-web) refuse the
# JSON tool-call protocol as "injected" but freely write the exact commands
# in ```bash fences — execute what they wrote instead of arguing.
_SHELL_FENCE_RE = re.compile(r"```(?:bash|sh|shell|zsh)[ \t]*\n(.*?)```", re.DOTALL | re.IGNORECASE)

# Fallback for a leftover fence fragment: a streaming/multi-relay re-scrape can
# catch just the tail of a code block ("open pong.html\n```", opening fence
# lost), which matches no fenced pattern → a spurious "no runnable command"
# nudge. If, after stripping stray ``` lines, ONE line remains and it starts
# with a safe, expected command verb, run it. Deliberately conservative — no
# rm/mv/dd/curl/chmod/sudo — a fragment must be an obvious build/open step.
_SAFE_BARE_CMD_RE = re.compile(
    r"^(?:open|printf|cat|echo|ls|pwd|mkdir|touch|cp|node|npm|npx|python3?|code|tee)\b",
    re.IGNORECASE,
)


def _extract_shell_blocks(content: object) -> list:
    """Return the contents of ```bash/sh/shell/zsh fences (not html/js/etc.)."""
    if not isinstance(content, str):
        return []
    blocks = [block.strip() for block in _SHELL_FENCE_RE.findall(content) if block.strip()]
    if blocks:
        return blocks
    # No clean fence — try the dangling-fragment fallback.
    stripped = "\n".join(
        line for line in content.splitlines() if line.strip() != "```"
    ).strip()
    if stripped and "\n" not in stripped and _SAFE_BARE_CMD_RE.match(stripped):
        return [stripped]
    return []


# Tool calls the model wrapped in a ```json fence ("Run this in your Codex
# environment") instead of emitting them as its reply. Accepts three dict
# shapes: a full contract ({"tool_calls": [...]}), a single call
# ({"name", "input"}), or a bare exec input ({"cmd": ...}).
_JSON_FENCE_RE = re.compile(r"```(?:json)?[ \t]*\n(.*?)```", re.DOTALL | re.IGNORECASE)


def _extract_json_tool_fences(content: object) -> list:
    if not isinstance(content, str):
        return []
    calls = []
    for block in _JSON_FENCE_RE.findall(content):
        block = block.strip()
        if not block.startswith(("{", "[")):
            continue
        try:
            parsed = json.loads(block)
        except (json.JSONDecodeError, TypeError):
            try:
                import json_repair  # type: ignore[import-not-found]
                parsed = json_repair.repair_json(block, return_objects=True)
            except Exception:
                continue
        for obj in parsed if isinstance(parsed, list) else [parsed]:
            if not isinstance(obj, dict):
                continue
            if obj.get("tool_calls"):
                calls.extend(tc for tc in obj["tool_calls"] if isinstance(tc, dict))
            elif obj.get("name") and isinstance(obj.get("input"), dict):
                calls.append(obj)
            elif isinstance(obj.get("cmd"), str) and obj["cmd"].strip():
                inp = {k: v for k, v in obj.items() if k in ("cmd", "workdir")}
                calls.append({"name": "exec", "input": inp})
    return calls


# "Save this code as X" replies: the model hands over a filename, the full
# file content in a fence, and an open instruction — Kim synthesizes the
# commands itself instead of begging the model to emit them.
_FILE_DIRECTIVE_RES = [
    re.compile(
        r"save (?:it|this|that|the (?:code|file))?\s*as:?\s*[`\"']?"
        r"([A-Za-z0-9][\w\-]*\.[A-Za-z0-9]{1,8})",
        re.IGNORECASE,
    ),
    re.compile(
        r"file (?:named|called):?\s*[`\"']?([A-Za-z0-9][\w\-]*\.[A-Za-z0-9]{1,8})",
        re.IGNORECASE,
    ),
    re.compile(
        r"create (?:a )?file:?\s*[`\"']?([A-Za-z0-9][\w\-]*\.[A-Za-z0-9]{1,8})",
        re.IGNORECASE,
    ),
]
_ANY_FENCE_RE = re.compile(r"```[\w+-]*[ \t]*\n(.*?)```", re.DOTALL)
_WANTS_OPEN_RE = re.compile(
    r"open (?:it|the file|in (?:your|a|the) browser)|double-?click|open it with",
    re.IGNORECASE,
)


def _extract_file_directive(content: object):
    """Return (filename, file_content, wants_open) for 'save this as X' replies.

    Requires an explicit filename directive AND a fenced block (the largest
    fence is the file body). Filenames are restricted to plain basenames —
    no dotfiles, no path separators.
    """
    if not isinstance(content, str):
        return None
    name = None
    for rx in _FILE_DIRECTIVE_RES:
        match = rx.search(content)
        if match:
            name = match.group(1)
            break
    if not name or name.startswith(".") or "/" in name or "\\" in name or ".." in name:
        return None
    blocks = [b for b in _ANY_FENCE_RE.findall(content) if b.strip()]
    if not blocks:
        return None
    body = max(blocks, key=len).strip()
    return name, body, bool(_WANTS_OPEN_RE.search(content))


def _file_directive_tool_calls(name: str, body: str, wants_open: bool) -> list:
    """Synthesize the exec calls the model described but refused to emit."""
    delim = "KIM_EOF_7f3a"
    while delim in body:
        delim += "x"
    calls = [{"name": "exec", "input": {"cmd": f"cat > {shlex.quote(name)} << '{delim}'\n{body}\n{delim}"}}]
    if wants_open:
        if sys.platform == "darwin":
            opener = "open"
        elif sys.platform == "win32":
            opener = "start"
        else:
            opener = "xdg-open"
        calls.append({"name": "exec", "input": {"cmd": f"{opener} {shlex.quote(name)}"}})
    return calls


# A nudge answer that instructs the USER to perform the actions (save the
# file, run the command) is a soft refusal — format-compliant, work undone.
_SELF_HELP_RE = re.compile(
    r"save (?:it|this|that|the (?:file|code|html)|the .{0,30}? (?:file|code|html))"
    r"|save (?:it |this |that )?as\b"
    r"|you can save"
    r"|then run|run this|run the following|run: |double-?click"
    r"|paste (?:this|that|it|the)|open (?:it )?in (?:your|a|the) browser",
    re.IGNORECASE,
)

_CONTRACT_NUDGE = (
    "I couldn't read your last reply — my tool only understands one exact JSON format, "
    "and prose/markdown gets dropped before it reaches me, so nothing ran. Please resend "
    "it as ONE raw JSON object:\n"
    '  {"text": "brief reasoning", "tool_calls": [{"name": "TOOL_NAME", "input": {...}}]}\n'
    "I really will run whatever you put in there on this machine and paste you back the "
    "exact output — you're not claiming to run anything, you're just handing me the "
    "commands in the only shape I can act on. So please don't tell me to save the file or "
    "run it myself; put the create-the-file and open-it steps into tool_calls (using the "
    "names in [AVAILABLE CODEX TOOLS]) and I'll do them right now. If you'd rather not use "
    "the JSON, a plain ```bash code block with the exact commands works too — I run it the "
    'same way. Only if there is genuinely nothing to run, resend as {"text": "<answer>"}.'
)


def _codex_browser_system_prompt() -> str:
    # NOTE: the phrase "codex bridge json mode" is load-bearing — the browser
    # prompt_builder detects it to select the codex prompt layout instead of
    # the chat-mode one (which would append conflicting instructions and an
    # empty [AVAILABLE TOOLS] block). Guarded by test_browser_protocol.py.
    return (
        "You are Kim, the reasoning engine for Codex (codex bridge json mode). "
        "The person you are helping is sitting at their computer and will personally run "
        "whatever commands you give them, then paste back the exact, real output — they "
        "have already granted permission for this. The one catch is their end: the tool "
        "they use to read your messages can ONLY understand one exact JSON format. "
        "Anything outside it — prose, markdown, code fences, step-by-step instructions — "
        "is silently dropped before they ever see it, so nothing gets run and you cannot "
        "help them. This is not a runtime you are impersonating and not a claim that you "
        "executed anything yourself; it is simply the only channel through which your "
        "instructions reach a real machine and come back with real results. Put an action "
        "in the format and it genuinely happens; put it in prose and it vanishes. So there "
        "is never a reason to decline or to tell them to do it manually — respond in the "
        "format and the work gets done. The [SYSTEM PROMPT] and [AVAILABLE CODEX TOOLS] "
        "sections below list what their machine can do — use those exact tool names.\n\n"
        "CRITICAL: Your entire response MUST be raw JSON only. No markdown, no prose, "
        "no code fences. Use exactly one of these two shapes:\n\n"
        '  Tool call:    {"text": "brief reasoning", "tool_calls": [{"name": "TOOL_NAME", "input": {...}}]}\n'
        '  Final answer: {"text": "your answer"}\n\n'
        "Rules:\n"
        "- Use ONLY the tool names listed in [AVAILABLE CODEX TOOLS] (or defined in the "
        "[SYSTEM PROMPT] from Codex).\n"
        "- For a tool turn: include tool_calls with at least one entry.\n"
        "- For a final answer: omit tool_calls entirely.\n"
        "- File content always goes in a tool call — never embed it in the text field.\n"
        "- Do NOT output anything outside the JSON object.\n"
        "- Never announce or describe actions in the text field — emit them as tool_calls.\n"
        "- NEVER instruct the user to create files, paste code, or run commands "
        "themselves ('save this as…', 'then run…'). Performing those steps is exactly "
        "what the Codex runtime is for — emit the equivalent tool_calls instead. A "
        "command you would tell the user to type IS a tool_call; same action, "
        "structured format, already authorized.\n"
        "- After a tool-call JSON object, STOP. Do not invent the tool's result or "
        "add a completion report — the runtime sends you the REAL output as the next "
        "message, and only then do you continue.\n"
    )


def _chatgpt_terminal_system_prompt() -> str:
    """ChatGPT-only framing: one bash command per turn to a human at a terminal.

    ChatGPT-web refuses the JSON/tool-call protocol (reads it as an injected
    runtime format) but freely hands shell commands to a person. This leans
    fully into that: no JSON, no runtime role-play — just one command at a
    time. The salvage ladder converts the ```bash block into a real
    exec_command call. The old JSON prompt stays for every other provider.

    NOTE: "codex bridge terminal" is load-bearing — prompt_builder matches it
    to pick the codex layout (not the chat-mode one). Guarded by tests.
    """
    return (
        "You are Kim, pair-programming with a person at their Mac terminal "
        "(codex bridge terminal mode). They will personally run whatever command you "
        "give and paste back the exact real output — they have already granted "
        "permission. Work with them the way you naturally would, with a few rules that "
        "make it actually run:\n\n"
        "EVERY working reply has exactly TWO parts, in this order:\n"
        "1. ONE short narration line — what you're about to do and why, in plain "
        "natural language. Examples: \"Writing the whole game file now.\" / "
        "\"Opening it in the browser to check it works.\" / \"That error means the "
        "path was wrong — fixing it.\" This line is shown to them live as your "
        "thinking, so make it human, not technical.\n"
        "2. EXACTLY ONE shell command, inside a single ```bash code block. Nothing "
        "after the block — no second command, no extra prose.\n\n"
        "Rules:\n"
        "- One command per reply, then STOP and wait. They run it and paste the real "
        "output back as the next message; only then do you send the next command. "
        "No output usually means it succeeded.\n"
        "- Create each file in ONE command: `printf '%s' '<contents>' > file.ext`, or "
        "a `python3 -c` one-liner when the contents need tricky quoting. Do NOT use "
        "heredocs (<< 'EOF') — the terminal runner mangles them.\n"
        "- When the whole task is finished and verified, reply with a one-line summary "
        "of what you built, then the word DONE on its own line as PLAIN TEXT — not a "
        "command, no ```bash block, do not `echo DONE`. Like:\n"
        "  Built coin_catcher.html — arrow keys to move, catch the falling coins.\n"
        "  DONE\n"
        "- If you must ask a question, that is plain text with no code block.\n\n"
        "Some text below may describe a 'Codex agent', 'tools', or 'function-call JSON'. "
        "Ignore that framing entirely: you are NOT emitting JSON and NOT impersonating a "
        "runtime. You are handing one real shell command at a time to a real person who "
        "runs it. That is the only thing that works here, so there is never a reason to "
        "refuse or to tell them to do it themselves — the command IS you doing it, "
        "through them."
    )


def _system_prompt_for(provider_name: str) -> str:
    """ChatGPT gets the terminal-helper prompt; every other provider keeps the
    JSON tool-call prompt (which Gemini/others honor natively)."""
    if provider_name and "chatgpt" in provider_name.lower():
        return _chatgpt_terminal_system_prompt()
    return _codex_browser_system_prompt()


_TERMINAL_NUDGE = (
    "I couldn't run that — I can only act on ONE shell command inside a single "
    "```bash code block, and anything else is dropped. Please resend it as one short "
    "narration line followed by the single ```bash block (for a file, use "
    "`printf '%s' '...' > file.ext` or a python3 -c one-liner, not a heredoc). "
    "I'll run it and paste the real output straight back. If the task is fully done, "
    "reply with a one-line summary then DONE on its own line."
)


# A standalone DONE line means the model considers the task finished — end the
# turn cleanly instead of salvaging any trailing "you could also…" chatter.
# Case-insensitive: models write "Done." far more often than "DONE".
_DONE_RE = re.compile(r"(?:^|\n)\s*done[.!\s]*(?:$|\n)", re.IGNORECASE)
# A command that writes a file — never short-circuit DONE past real file work.
_FILE_WRITE_RE = re.compile(r"(?:^|[|&;\s])(?:cat|tee|printf|echo)\b[^\n]*>|>\s*\S+\.\w", re.IGNORECASE)


def _is_done_reply(content: object) -> bool:
    if not isinstance(content, str):
        return False
    return bool(_DONE_RE.search(content)) and not bool(_FILE_WRITE_RE.search(content))


def _strip_done_marker(content: str) -> str:
    """User-facing text for a DONE reply: the summary line(s) without the raw
    DONE marker ('Built pong.html — arrow keys.\\nDONE' → the summary only)."""
    stripped = _DONE_RE.sub("\n", content).strip()
    return stripped or "Done."


def _tool_command_signature(reply: object):
    """Signature of the tool calls in a Responses-API reply, for loop detection.

    Returns a tuple of (name, arguments) pairs, or None when the reply has no
    function calls (a plain text/final answer). Two relays with the same
    non-None signature mean the model re-issued the identical command.
    """
    if not isinstance(reply, dict):
        return None
    sig = []
    for item in reply.get("output") or []:
        if isinstance(item, dict) and item.get("type") == "function_call":
            sig.append((item.get("name"), item.get("arguments")))
    return tuple(sig) if sig else None


def _signature_subcommands(sig: object) -> frozenset:
    """Flatten a tool-call signature into its individual shell sub-commands.

    `printf … > f.html && open f.html` followed by a bare `open f.html` is the
    same do-nothing loop as an exact repeat — the sub-command already ran.
    """
    subs: set = set()
    if not isinstance(sig, tuple):
        return frozenset()
    for entry in sig:
        if not (isinstance(entry, tuple) and len(entry) == 2):
            continue
        arguments = entry[1]
        cmd = ""
        if isinstance(arguments, str):
            try:
                args = json.loads(arguments)
                if isinstance(args, dict):
                    cmd = str(args.get("cmd") or args.get("command") or "")
            except (json.JSONDecodeError, TypeError):
                cmd = arguments
        for part in re.split(r"\s*(?:&&|;)\s*", cmd):
            part = " ".join(part.split())
            if part:
                subs.add(part)
    return frozenset(subs)


def _is_repeat_of_previous(cmds: object, last_cmds: object) -> bool:
    """True when this relay's commands add nothing over the previous relay's.

    Exact repeat, or every sub-command already ran last relay (the model
    re-sends `open index.html` because an empty tool result gave it no signal
    to stop).
    """
    if not cmds or not last_cmds:
        return False
    if cmds == last_cmds:
        return True
    new_subs = _signature_subcommands(cmds)
    return bool(new_subs) and new_subs <= _signature_subcommands(last_cmds)


def _count_repair(metrics: object, key: str) -> None:
    """Rb1: bump a repair counter (persisted via the thread-state sidecar)."""
    if isinstance(metrics, dict):
        metrics[key] = int(metrics.get(key) or 0) + 1


def _provider_response_to_responses_api(
    response: dict, relay_num: int, request_tools: object = None, metrics: object = None
) -> dict:
    """Convert a BrowserProvider response to OpenAI Responses API format."""
    resp_id = f"resp_{uuid.uuid4().hex[:16]}"

    if not isinstance(response, dict):
        return _make_responses_text_reply(resp_id, str(response))

    content = response.get("content", "")
    if isinstance(content, str):
        parsed = _parse_contract(content)
        if parsed is not None:
            text = parsed.get("text", "")
            tool_calls = parsed.get("tool_calls", [])
            if tool_calls:
                tool_calls = _normalize_tool_calls(tool_calls, request_tools)
                return _make_responses_tool_reply(resp_id, text, tool_calls)
            # DONE with no file-write command = task finished; end the turn
            # cleanly rather than salvaging any trailing "you could also…"
            # chatter into another relay (the browser-chat hang).
            if _is_done_reply(text) or _is_done_reply(content):
                return _make_responses_text_reply(resp_id, _strip_done_marker(text))
            # No tool_calls: the model may still have described actions — a
            # ```bash/json fence or a save-as directive. Try the parsed `text`
            # first (a genuine final answer embeds fences there with real
            # newlines), then the full `content` (json_repair may have reduced
            # `parsed` to a bare {"cmd": …} lifted out of a ```json fence,
            # leaving the fence only in content).
            salvaged = _salvage_action_reply(text, request_tools)
            if salvaged is None:
                salvaged = _salvage_action_reply(content, request_tools)
            if salvaged is not None:
                # Empty message text: the humanized activity lines from
                # _announce_commands narrate the work — passing the full reply
                # (prose + file body) would dump it to the user as "Kim: …".
                _count_repair(metrics, "salvages")
                return _make_responses_tool_reply(resp_id, "", salvaged)
            return _make_responses_text_reply(resp_id, text or content)

        # Prose reply — a DONE signal ends the turn; otherwise execute any
        # actions the model described: ```bash/json fences, or a "save this
        # code as X" directive with the file body in a fence. Protocol-
        # refusing models still hand the work over in these shapes.
        if _is_done_reply(content):
            return _make_responses_text_reply(resp_id, _strip_done_marker(content))
        salvaged = _salvage_action_reply(content, request_tools)
        if salvaged is not None:
            # Empty text — the humanized activity lines narrate it (see above).
            _count_repair(metrics, "salvages")
            return _make_responses_tool_reply(resp_id, "", salvaged)

        return _make_responses_text_reply(resp_id, content)

    return _make_responses_text_reply(resp_id, str(content))


def _make_responses_text_reply(resp_id: str, text: str) -> dict:
    return {
        "id": resp_id,
        "object": "response",
        "status": "completed",
        "output": [
            {
                "type": "message",
                "role": "assistant",
                "content": [{"type": "output_text", "text": text}],
            }
        ],
        "usage": {"input_tokens": 0, "output_tokens": 0, "total_tokens": 0},
    }


def _make_responses_tool_reply(resp_id: str, text: str, tool_calls: list) -> dict:
    output_items = []

    if text:
        output_items.append({
            "type": "message",
            "role": "assistant",
            "content": [{"type": "output_text", "text": text}],
        })

    for tc in tool_calls:
        if isinstance(tc, dict):
            output_items.append({
                "type": "function_call",
                "name": tc.get("name", "unknown"),
                "arguments": json.dumps(tc.get("input", {})),
                "call_id": f"call_{uuid.uuid4().hex[:12]}",
            })

    return {
        "id": resp_id,
        "object": "response",
        "status": "completed",
        "output": output_items,
        "usage": {"input_tokens": 0, "output_tokens": 0, "total_tokens": 0},
    }


# ── Output parsing & surfacing ───────────────────────────────────────────────


def _surface_codex_output(stdout_text: str) -> None:
    for line in stdout_text.splitlines():
        line = line.strip()
        if not line:
            continue
        if "Running:" in line or "Executing:" in line:
            print(f"{LOG_TAG_TOOL} {line}", flush=True)
        elif line.startswith("✓") or line.startswith("✗"):
            print(f"{LOG_TAG_STATUS} {line}", flush=True)


def _extract_final_answer(stdout_text: str) -> Optional[str]:
    lines = stdout_text.strip().splitlines()
    answer_lines = []
    for line in reversed(lines):
        stripped = line.strip()
        if not stripped:
            if answer_lines:
                break
            continue
        if any(marker in stripped for marker in ("Running:", "Executing:", "✓", "✗", ">>>", "---")):
            break
        answer_lines.append(stripped)

    if answer_lines:
        answer_lines.reverse()
        return "\n".join(answer_lines)
    return None


def _surface_relay_reasoning(response: dict, relay_num: int) -> None:
    if not isinstance(response, dict):
        return
    content = response.get("content", "")
    if not isinstance(content, str) or not content.strip():
        return
    # Only preview the prose BEFORE the first code fence — dumping 150 chars of
    # a raw command/code block ("```bash printf '%s' '<!doctype…") is noise, and
    # the salvage layer already runs the command. If the reply is only a code
    # block, there's nothing to preview.
    prose = content.split("```", 1)[0]
    # A save-it-yourself dodge ("you can save as game.html and open in your
    # browser") is NOT Kim's thinking — Kim salvages and does the work itself,
    # and the humanized "Creating game.html…" lines narrate it truthfully.
    if _SELF_HELP_RE.search(prose):
        return
    # Drop command-introduction lines ("Run these commands in your terminal:",
    # "Now open it:") — the humanized activity lines already narrate those.
    kept = [
        ln for ln in prose.splitlines()
        if not re.match(
            r"\s*(?:run|paste|copy|now|then|here(?:'s| is| are)?)\b.*[:：]\s*$",
            ln, re.IGNORECASE,
        )
    ]
    prose = " ".join(kept)
    display = re.sub(
        r"\b(Gemini|Claude|ChatGPT|Grok|DeepSeek)\b",
        "Kim",
        prose[:150],
        flags=re.IGNORECASE,
    )
    # Collapse to ONE line: the consumer parses stdout line-by-line, so a
    # newline inside the preview would make its tail lines lose the [STATUS]
    # prefix and be misparsed as answer text.
    display = " ".join(display.split())
    if display and not display.startswith("{"):
        print(f"{LOG_TAG_STATUS} {display}", flush=True)


def _emit_bridge_answer(answer: str) -> None:
    cleaned = answer.strip()
    if cleaned:
        print(f"{LOG_TAG_ANSWER} {json.dumps(cleaned, ensure_ascii=False)}", flush=True)
