#!/usr/bin/env python3
"""Generate docs/ENVIRONMENT.md — the canonical KIM_* environment-variable reference.

Scans the code directories for `KIM_[A-Z_]+` identifiers that appear in an
environment-access context (a line mentioning "env": os.environ / os.getenv /
std::env::var / option_env! / process.env / Command::env / env dicts) and
emits a table of variable -> files that reference it.

The Description column is HAND-CURATED: on regeneration the script re-reads
the existing docs/ENVIRONMENT.md, extracts descriptions keyed by variable
name, and carries them forward. Newly discovered variables get
"TODO — undocumented". Edit descriptions in docs/ENVIRONMENT.md directly
(never the table structure), then re-run this script to refresh file lists.

Usage:  python scripts/gen_env_reference.py        # rewrite docs/ENVIRONMENT.md
        python scripts/gen_env_reference.py --check # exit 1 if the doc is stale

Stdlib-only; idempotent (running twice produces no diff).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "docs" / "ENVIRONMENT.md"

SCAN_DIRS = [
    "orchestrator",
    "mcp_server",
    "codex_engine",
    "kimctl",
    "desktop/src-tauri/src",
    "cli/src",
]
EXTENSIONS = {".py", ".rs", ".ts", ".tsx", ".js"}
SKIP_DIR_NAMES = {"__pycache__", "node_modules", "target", ".git"}

# KIM_… identifier not glued to a preceding word char (filters __KIM_HREF__-style
# UI sentinels); trailing underscores are stripped after matching.
VAR_RE = re.compile(r"(?<![A-Za-z0-9_])KIM_[A-Z][A-Z0-9_]*")
# A variable counts as an env var only if at least one line referencing it also
# mentions "env" (os.environ, std::env::var, option_env!, process.env, .env(...)).
ENV_CONTEXT_RE = re.compile(r"env", re.IGNORECASE)

MAX_FILES_SHOWN = 4
TODO_DESC = "TODO — undocumented"

HEADER = """\
# Kim environment variables (`KIM_*`)

<!-- GENERATED by scripts/gen_env_reference.py — descriptions are hand-curated
     and preserved across regens; do not edit the table structure by hand.
     To refresh the file lists after code changes: python scripts/gen_env_reference.py -->

This is the canonical reference for every `KIM_*` environment variable read by
the codebase ({count} variables at last generation). The **Read in** column is
generated from the source; the **Description** column is hand-curated — edit it
here and re-run the generator, which preserves descriptions by variable name.
Variables marked "{todo}" are internal or not yet documented; verify against
the listed source files before relying on them.

| Variable | Read in | Description |
|---|---|---|
"""


def iter_source_files():
    for d in SCAN_DIRS:
        base = REPO_ROOT / d
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*")):
            if not path.is_file() or path.suffix not in EXTENSIONS:
                continue
            if any(part in SKIP_DIR_NAMES for part in path.parts):
                continue
            yield path


def collect_vars() -> dict[str, list[str]]:
    """Return {var_name: sorted list of repo-relative files with env-context hits}."""
    hits: dict[str, set[str]] = {}
    for path in iter_source_files():
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        rel = path.relative_to(REPO_ROOT).as_posix()
        for line in text.splitlines():
            names = {m.group(0).rstrip("_") for m in VAR_RE.finditer(line)}
            if not names or not ENV_CONTEXT_RE.search(line):
                continue
            for name in names:
                hits.setdefault(name, set()).add(rel)
    return {name: sorted(files) for name, files in sorted(hits.items())}


def parse_existing_descriptions() -> dict[str, str]:
    """Pull var -> description out of the current docs/ENVIRONMENT.md, if any."""
    descriptions: dict[str, str] = {}
    if not OUTPUT.is_file():
        return descriptions
    row_re = re.compile(r"^\|\s*`(KIM_[A-Z0-9_]+)`\s*\|.*\|\s*(.*?)\s*\|\s*$")
    for line in OUTPUT.read_text(encoding="utf-8").splitlines():
        m = row_re.match(line)
        if m:
            descriptions[m.group(1)] = m.group(2)
    return descriptions


def format_files(files: list[str]) -> str:
    shown = files[:MAX_FILES_SHOWN]
    cell = ", ".join(f"`{f}`" for f in shown)
    extra = len(files) - len(shown)
    if extra > 0:
        cell += f" (+{extra} more)"
    return cell


def render(var_files: dict[str, list[str]], descriptions: dict[str, str]) -> str:
    out = [HEADER.format(count=len(var_files), todo=TODO_DESC)]
    for name, files in var_files.items():
        desc = descriptions.get(name, "").strip() or TODO_DESC
        desc = desc.replace("|", "\\|").replace("\n", " ")
        out.append(f"| `{name}` | {format_files(files)} | {desc} |\n")
    return "".join(out)


def main() -> int:
    check_only = "--check" in sys.argv[1:]
    var_files = collect_vars()
    descriptions = parse_existing_descriptions()
    content = render(var_files, descriptions)
    old = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else None
    if check_only:
        if old != content:
            print(f"STALE: {OUTPUT} does not match the code; re-run {sys.argv[0]}")
            return 1
        print(f"OK: {OUTPUT} is up to date ({len(var_files)} variables)")
        return 0
    if old == content:
        print(f"Unchanged: {OUTPUT} ({len(var_files)} variables)")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT} ({len(var_files)} variables)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
